[project]
name = "brickkit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ty>=0.0.11",
]

[project.optional-dependencies]
dev = [
    "claudetracing>=0.2.0",
]
